### PR TITLE
Drop ProofTree in favor of non-recursive approach

### PR DESCRIPTION
**Pull request by pipermerriam**
## What was wrong?

The `ProofTree` has been bugging me.  It's recursive by nature and involved un-necessary extra computation.

## How was it fixed?

Direct implementation of merklization as well as navigating the proof elements without walking a tree.

#### Cute Animal Picture

red-panda-hero-5

### CODE REVIEW

**Comment by pipermerriam** [comment]
Things that I think are better now.

1. Proofs don't have a `hash_tree_root` property anymore.  This fixes the foot-gun where a proof's elements *might* not actually represent the `hash_tree_root` and if someone forgot to call `validate_proof(proof)` then they might be working with an invalid proof.
2. I don't think anything is actually recursive anymore.
3. The various methods for navigating the tree like `Proof.get_data_elements()` no longer need to "walk" the tree which was an expensive way to generate proof elements.
4. Much more granular tests which catch previous off-by-one errors that were going undetected by the test suite.

**Comment by pipermerriam** [comment]
Ok, here's the big-win numbers.  TLDR  3-4x speed increase.

### Benchmark using Tree approach

```
+-------+--------+---------+------------+------------+
| name  |  size  | elapsed | proofs/sec | iterations |
+=======+========+=========+============+============+
| 0b    |      0 |   0.303 |   3305.073 |       1000 |
+-------+--------+---------+------------+------------+
| 128b  |    128 |   0.321 |   3119.925 |       1000 |
+-------+--------+---------+------------+------------+
| 256b  |    256 |   0.359 |   2783.899 |       1000 |
+-------+--------+---------+------------+------------+
| 512b  |    512 |   0.458 |   2183.154 |       1000 |
+-------+--------+---------+------------+------------+
| 1kb   |   1024 |   0.329 |   1520.218 |        500 |
+-------+--------+---------+------------+------------+
| 2kb   |   2048 |   0.321 |    933.607 |        300 |
+-------+--------+---------+------------+------------+
| 4kb   |   4096 |   0.445 |    449.122 |        200 |
+-------+--------+---------+------------+------------+
| 10kb  |  10240 |   0.549 |    182.092 |        100 |
+-------+--------+---------+------------+------------+
| 20kb  |  20480 |   0.795 |     88.026 |         70 |
+-------+--------+---------+------------+------------+
| 100kb | 102400 |   1.134 |     17.644 |         20 |
+-------+--------+---------+------------+------------+
```

### Benchmark using this new approach

```
+-------+--------+---------+------------+------------+
| name  |  size  | elapsed | proofs/sec | iterations |
+=======+========+=========+============+============+
| 0b    |      0 |   0.114 |   8800.705 |       1000 |
+-------+--------+---------+------------+------------+
| 128b  |    128 |   0.119 |   8432.538 |       1000 |
+-------+--------+---------+------------+------------+
| 256b  |    256 |   0.132 |   7564.915 |       1000 |
+-------+--------+---------+------------+------------+
| 512b  |    512 |   0.160 |   6247.456 |       1000 |
+-------+--------+---------+------------+------------+
| 1kb   |   1024 |   0.111 |   4514.900 |        500 |
+-------+--------+---------+------------+------------+
| 2kb   |   2048 |   0.104 |   2875.224 |        300 |
+-------+--------+---------+------------+------------+
| 4kb   |   4096 |   0.121 |   1655.240 |        200 |
+-------+--------+---------+------------+------------+
| 10kb  |  10240 |   0.152 |    659.891 |        100 |
+-------+--------+---------+------------+------------+
| 20kb  |  20480 |   0.197 |    355.707 |         70 |
+-------+--------+---------+------------+------------+
| 100kb | 102400 |   0.295 |     67.861 |         20 |
+-------+--------+---------+------------+------------+
```

**Review by marcgarreau — APPROVED** [review]
Still digesting bits of this, but in general it looks like a solid improvement 🚀 

The navigation/chunk utils are easier to compartmentalize and grok, feels better that proofs generate their own root, and the great test visualizations continue to be the quickest way to understand the world 🌈

**Comment by pipermerriam** [comment]
@lithp happy to do post-review cleanup if you have any additional comments.

**Pull request merged**
